### ISSUE TITLE
Figure out MPB/OSB fine tune

### ISSUE THREAD

**Issue by dakrk** [dakrk/manatools#2]
Not quite sure how fine tune works yet, and I think I remember observing some differences in how it's done on version 1 files.

**Comment by PiKeyAr** [comment]
I remember it having effects on pitch so it might be affecting sample rate together with base note etc.?

**Comment by dakrk** [comment]
Hmm, I should think fine tune would affect pitch like that, what I'm not so sure of at the moment is more so what units they're measured in

**Comment by dakrk** [comment]
c9b44ca3e1c811d35de24f8251f161ea39843d71 documents and 97e1a819827c32012bd5448e2616d83c0300e041 now exports the supposed -48 cents -> 47 cents range to the MPB -> SF2 conversion, meaning this is practically resolved ("practically" because I'm not sure the range I have is *exactly* equal to what it uses, but it seems to sound indistinguishable to the ear).

I don't remember where I got OSB from in the issue title though, because that doesn't even have fineTune in the hexpat, unless that's just a guess from the 24 undocumented bytes (which could be likely, because the structure of an OSB program compared to an MPB split is the same, up until it gets to all the start/end/base note data which is where the 24 undocumented OSB bytes start).
